name: minify-plugins-action
on:
  pull_request:
    branches:
      - master
jobs:
  check-minified-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v2.1.2
      - uses: actions/checkout@v2
      - run: |
          npm install
          npm run minify
          if [[ -n "$(git status -s)" ]]; then
              echo "The minfiles in the plugins are not updated. Please update them before merging this.";
              exit 1;
          fi
        working-directory: utils/minify_plugins/