name: minify-plugins-action
on:
  pull_request:
    branches:
      - master
jobs:
  check-minified-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.1.2
      - run: ./utils/minify_plugins/check-minified-files.sh
