name: Docker Image CI

on:
  push:
    branches: [ "master" ]
    paths:
      - base-containers/**

jobs:

  build-and-push-inginious-c-base:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - uses: mr-smithers-excellent/docker-build-push@v5
      name: Build & push Docker image inginious-c-base
      with:
        image: unjudge/inginious-c-base
        tags: latest
        registry: docker.io
        directory: ./base-containers/base
        dockerfile: ./base-containers/base/Dockerfile
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        
  build-and-push-inginious-c-default:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - uses: mr-smithers-excellent/docker-build-push@v5
      name: Build & push Docker image inginious-c-default
      with:
        image: unjudge/inginious-c-default
        tags: latest
        registry: docker.io
        directory: ./base-containers/default
        dockerfile: ./base-containers/default/Dockerfile
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
